version: "3.3"

services:
  dedipoc-api:
    build:
      context: ./dedipoc-api/
    ports:
      - 3001:3001
    environment:
      - SERVICE_NAME=Dedipoc API
      - SERVER_PORT=3001
      - DATABASE_USERNAME=dedipoc
      - DATABASE_PASSWORD=sausages
      - DATABASE_CLUSTER=dedipoc-db
      - DATABASE_NAME=dedipoc-db
      - DATABASE_AUTH=admin-dedipoc-db
      - DATABASE_PORT=27017
      - SESSION_SECRET=0eaV6dfLvD
      - STORE_SECRET=TIrC3HL2Pt
    volumes:
      - /app/node_modules
      - "$MEDIA_REPOSITORY:/app/media"
      - ./dedipoc-api/src:/app/src
      - ./logs:/app/logs
    depends_on:
      - dedipoc-db
    restart: always

  dedipoc-db:
    image: mongo:4.2.8
    environment:
      - MONGO_INITDB_DATABASE=admin-dedipoc-db
    ports:
      - 27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    restart: always

  dedipoc:
    stdin_open: true
    build:
      context: ./dedipoc/
    volumes:
      - /app/node_modules
      - ./dedipoc:/app
      - shared:/app/build
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    depends_on:
      - dedipoc
      - dedipoc-api
    ports:
      - "$NGINX_PORT:80"
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - shared:/usr/share/nginx/html
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email dedipoc@gmail.com -d dedipoc.fr --agree-tos
volumes:
  mongodb:
  mongodb_config:
  shared:

